version: "3.8"
services:
  backend:
    build: .
    depends_on:
      - database
    ports:
      - "5000:5000"
    volumes:
      - ./:/backend/src/app/
      - /backend/src/app/node_modules

  database:
    image: postgres:15-alpine
    restart: always
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=pass
      - POSTGRES_DB=blogify
    ports:
      - "5432:5432"
    volumes:
      - /database/var/lib/postgresql/data
